### ISSUE TITLE
Question: Get-AutomationVariable strangeness

### ISSUE THREAD

**Issue by mortenlerudjordet** [randorfer/ScorchDev#1]
Hey, just wanted to reach out and see if you see the same behavior as me using Get-AutomationVariable in SMA.

Just as a preface the SMA environment I'm testing on is fully updated with the last version of all things SMA. 

So I have done a lot of testing and head scratching lately. So in essence I can only get Get-AutomatonVariable to work if I call it direclty from the Workflow. 

If I move the call to a function inside the workflow, the call will not produce anything. Just an empty value, and no indication of that there was problems with the call. It just silently fails. 

So as a workaround I made a function that uses Get-SMAVariable, and finds all variables with a desired prefix (like ActiveDirectory). Return this list to the Workflow and then call Get-AutomationVariable with the Names of the variable set I want.

I guess you can use Get-SMAVariable directly, but from what I have discovered encrypted values will not be accessible in its original form that way.

What is your experience on this front?

Thanks!

**Comment by mortenlerudjordet** [comment]
What I tested had a bit more logic to it, but the essence is the same as below. 

In code:

Workflow Working {
   # Gets the variable as expected
    Get-AutomationVariable -Name "something" 
}

Workflow NotWorking {
         Function Get-SMAVar {
                Return Get-AutomationVariable -Name "something" 
          }
   # Return has no value
   $var = Get-SMAVar 
}

**Comment by randorfer** [comment]
you cannot use the get-automationvariable functions inside of inlinescripts and you are correct, the web service functions do not pull encrypted assets. You have to access encrypted assets directly. I don't check this all that often you can email me at Ryan.Andorfer[at]genmills.com

**Comment by randorfer** [comment]
taking this offline
